# devise/config/E07_FS.yaml
# Surcharge config_base.yaml — seules les clés spécifiques à cette API sont définies

api_id:     "E07_FS"

input:
  type:       "sqlserver"
  table_name: "E7EtatBcmFluxSortants"

columns:
  field:           "Pays"
  field_out:       "Pays_iso2"
  ref_transaction: "ReferenceTransaction"
  ref_banque:      "RefBanque"

outlier_tag: "OUTLIER"
use_llm:     true

output:
  dir: "pays/outputs/E07_FS/"
