# devise/config/E07_FS.yaml
# Surcharge config_base.yaml — seules les clés spécifiques à cette API sont définies

api_id:     "E07_FS"

input:
  type:       "sqlserver"
  table_name: "E7EtatBcmFluxSortants"

columns:
  field:           "ModeReglement"
  field_out:       "ModeReglement_Normalisé"
  ref_transaction: "ReferenceTransaction"
  ref_banque:      "RefBanque"

outlier_tag:      "OUTLIER"
referentiel_path: "mode_reglement/referentiel/mode_reglement_referentiel.json"

output:
  dir: "mode_reglement/outputs/E07_FS/"
