# pays/config/E10_FE.yaml
# Surcharge config_base.yaml

api_id:  "E10_FE"

input:
  type:       "sqlserver"
  table_name: "E10EtatBcmFluxEntrants"

columns:
  field:           "ModeReglement"
  field_out:       "ModeReglement_iso"
  ref_transaction: "ReferenceTransaction"
  ref_banque:      "RefBanque"

outlier_tag:      "OUTLIER"
referentiel_path: "mode_reglement/referentiel/mode_reglement_referentiel.json"

output:
  dir: "mode_reglement/outputs/E10_FE/"
