# typeswift/config/E07_FS.yaml
api_id:     "E07_FS"
flux_type:  "FS"

input:
  type:       "sqlserver"
  table_name: "E7EtatBcmFluxSortants"

columns:
  field:           "TypeSwfit"
  field_out:       "TypeSwift_Normalisé"
  ref_transaction: "ReferenceTransaction"
  ref_banque:      "RefBanque"

outlier_tag:      "OUTLIER"
referentiel_path: "typeswift/referentiel/typeswift_referentiel.json"

output:
  dir: "typeswift/outputs/E07_FS/"