# pays/config/E10_FE.yaml
# Surcharge config_base.yaml

api_id:  "E10_FE"
flux_type:  "FS"

input:
  type:       "sqlserver"
  table_name: "E10EtatBcmFluxEntrants"

columns:
  field:           "TypeSwfit"
  field_out:       "TypeSwift_Normalisé"
  ref_transaction: "ReferenceTransaction"
  ref_banque:      "RefBanque"

outlier_tag:      "OUTLIER"
referentiel_path: "typeswift/referentiel/typeswift_referentiel.json"

output:
  dir: "typeswift/outputs/E10_FE/"

